blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),  # rename to article-list?
    url(r'^new$', views.ArticleCreateView.as_view(), name='article-new'),
    # url(r'^(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(), name='article-detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.article_detail, name='article-detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.ArticleUpdateView.as_view(), name='article-edit'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.ArticleDeleteView.as_view(), name='article-delete'),
    url(r'^(?P<article_id>[0-9]+)/comments/(?P<comment_id>[0-9]+)/delete$', views.CommentDeleteView.as_view(), name='comment-delete'),
]

django_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
]

blog/models.py
from django.core.urlresolvers import reverse
from django.core.validators import MinLengthValidator
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200, validators=[MinLengthValidator(5)])
    text = models.TextField()

    def __unicode__(self):  # __str__ on Python 3
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article-detail', args=[str(self.id)])


class Comment(models.Model):
    article = models.ForeignKey(Article)
    commenter = models.CharField(max_length=200, validators=[MinLengthValidator(5)])
    text = models.TextField()

    def __unicode__(self):  # __str__ on Python 3
        return self.text

blog/forms.py
from django.forms import ModelForm
from blog.models import Article, Comment


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['commenter', 'text']

blog/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from blog.forms import ArticleForm, CommentForm
from blog.models import Article, Comment


class ArticleMixin(object):
    model = Article
    form_class = ArticleForm  # also one can use fields = ['title', 'text']


class IndexView(ArticleMixin, generic.ListView):
    template_name = 'blog/articles/article_list.html'
    # context_object_name = 'article_list'


# class ArticleDetailView(ArticleMixin, generic.DetailView):
#     pass


def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.article = article
        comment.save()
        return redirect(article)
    return render(request, 'blog/articles/article_detail.html', {'form': form, 'object': article})


class ArticleCreateView(ArticleMixin, generic.CreateView):
    template_name = 'blog/articles/article_new.html'


class ArticleUpdateView(ArticleMixin, generic.UpdateView):
    template_name = 'blog/articles/article_edit.html'


# def article_delete(request, pk):
#     article = get_object_or_404(Article, pk=pk)
#     if request.method == 'POST':
#         article.delete()
#         return redirect('blog:index')
#
#     return render(request, 'blog/articles/article_confirm_delete.html', {'object': article})


class ArticleDeleteView(ArticleMixin, generic.DeleteView):
    template_name = 'blog/articles/article_confirm_delete.html'
    success_url = reverse_lazy('blog:index')  # or use get_success_url with a regular reverse


# def comment_delete(request, article_id, comment_id):
#     article = get_object_or_404(Article, pk=article_id)
#     comment = get_object_or_404(article.comment_set, pk=comment_id)
#     if request.method == 'POST':
#         comment.delete()
#         return redirect(article)
#
#     return render(request, 'blog/comments/comment_confirm_delete.html', {'object': comment})


class CommentDeleteView(generic.DeleteView):
    model = Comment
    template_name = 'blog/comments/comment_confirm_delete.html'
    pk_url_kwarg = 'comment_id'

    def get_queryset(self):
        article = get_object_or_404(Article, pk=self.kwargs['article_id'])
        return article.comment_set  # or Comment.objects.filter(article=article)

    def get_success_url(self):
        return self.object.article.get_absolute_url()

blog/templates/blog/article_detail.html
<p>
    <strong>Title:</strong>
    {{ object.title }}
</p>

<p>
    <strong>Text:</strong>
    {{ object.text }}
</p>

<h2>Comments</h2>
{% for comment in object.comment_set.all %}
    {% include "blog/comment_detail.html" %}
{% empty %}
    <p>No comments yet.</p>
{% endfor %}

<h2>Add a comment:</h2>
{% include "blog/comment_form.html" %}

<a href="{% url 'blog:article-edit' object.id %}">Edit</a> |
<a href="{% url 'blog:index' %}">Back</a>

blog/templates/blog/article_edit.html
<h1>Edit article</h1>

{% include "blog/article_form.html" %}

<a href="{% url 'blog:index' %}">Back</a>

blog/templates/blog/article_new.html
<h1>New article</h1>

{% include "blog/article_form.html" %}

<a href="{% url 'blog:index' %}">Back</a>

blog/templates/blog/articles/article_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p> Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Submit"/>
</form>

blog/templates/blog/articles/article_detail.html
<p>
    <strong>Title:</strong>
    {{ object.title }}
</p>

<p>
    <strong>Text:</strong>
    {{ object.text }}
</p>

<h2>Comments</h2>
{% for comment in object.comment_set.all %}
    {% include "blog/comments/comment_detail.html" %}
{% empty %}
    <p>No comments yet.</p>
{% endfor %}

<h2>Add a comment:</h2>
{% include "blog/comments/comment_form.html" %}

<a href="{% url 'blog:article-edit' object.id %}">Edit</a> |
<a href="{% url 'blog:index' %}">Back</a>

blog/templates/blog/articles/article_edit.html
<h1>Edit article</h1>

{% include "blog/articles/article_form.html" %}

<a href="{% url 'blog:index' %}">Back</a>

blog/templates/blog/articles/article_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit Article" />
</form>

blog/templates/blog/articles/article_list.html
<h1>Articles</h1>

<a href="{% url 'blog:article-new' %}">New Article</a>

<ul>
    {% for article in object_list %}
        <li>
            <span>{{ article.title }}</span>
            <a href="{% url 'blog:article-detail' article.id %}">Show</a>
            <a href="{% url 'blog:article-edit' article.id %}">Edit</a>
            <a href="{% url 'blog:article-delete' article.id %}">Delete</a>
        </li>
    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}
</ul>

blog/templates/blog/articles/article_new.html
<h1>New article</h1>

{% include "blog/articles/article_form.html" %}

<a href="{% url 'blog:index' %}">Back</a>

blog/templates/blog/comments/comment_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p> Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Submit"/>
</form>

blog/templates/blog/comments/comment_detail.html
<p>
    <strong>Commenter:</strong>
    {{ comment.commenter }}
</p>

<p>
    <strong>Comment:</strong>
    {{ comment.text }}
</p>

<p>
    <a href="{% url 'blog:comment-delete' object.id comment.id %}">Delete</a>
</p>

blog/templates/blog/comments/comment_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit Comment"/>
</form>